In [1]:
import pandas as pd
import numpy as np
from pandas.core._numba.kernels import mean_

fitness_data = {
    "Player": ["Rashford", "Casemiro", "Shaw", "Martinez"],
    "Heart_Rate_Avg": [145, 152, np.nan, 148],
    "Matches_Missed": [0, np.nan, 12, 5]
}
df = pd.DataFrame(fitness_data)

In [2]:
df

     Player  Heart_Rate_Avg  Matches_Missed
0  Rashford           145.0             0.0
1  Casemiro           152.0             NaN
2      Shaw             NaN            12.0
3  Martinez           148.0             5.0

In [9]:
df["Heart_Rate_Avg"] = df["Heart_Rate_Avg"].fillna(df["Heart_Rate_Avg"].mean())

In [7]:
df["Matches_Missed"] = df["Matches_Missed"].fillna(0)

In [8]:
df

     Player  Heart_Rate_Avg  Matches_Missed
0  Rashford           145.0             0.0
1  Casemiro           152.0             0.0
2      Shaw             NaN            12.0
3  Martinez           148.0             5.0

In [10]:
import pandas as pd

match_data = {
    "Player": ["Vinicius Jr", "Rashford", "Rodrygo", "Hojlund", "Vinicius Jr"],
    "Club": ["Real Madrid", "Manchester United", "Real Madrid", "Manchester United", "Real Madrid"],
    "Shots_On_Target": [3, 2, 1, 2, 4],
    "Expected_Goals_xG": [0.8, 0.4, 0.2, 0.5, 1.1]
}
df = pd.DataFrame(match_data)

In [11]:
club_offensive_output = df.groupby("Club").agg({
    "Shots_On_Target": 'sum',
    "Expected_Goals_xG": 'mean',
})

In [12]:
club_offensive_output

                   Shots_On_Target  Expected_Goals_xG
Club
Manchester United                4               0.45
Real Madrid                      8               0.70

In [13]:
import pandas as pd
import numpy as np

defense_data = {
    "Player": ["Militao", "Martinez", "Rudiger", "Varane"],
    "Tackles_Attempted": [40, 55, 38, 42],
    "Tackles_Won": [30, 48, 35, 29]
}
df = pd.DataFrame(defense_data)

In [15]:
df["Tackle_Success_Rate"] = df["Tackles_Won"] / df["Tackles_Attempted"]

In [18]:
df["Elite_Tackler"] = np.where((df["Tackle_Success_Rate"] > 0.8),1,0)

In [19]:
df

,Player,Tackles_Attempted,Tackles_Won,Tackle_Success_Rate,Elite_Tackler
0,Militao,40,30,0.750000,0
1,Martinez,55,48,0.872727,1
2,Rudiger,38,35,0.921053,1
3,Varane,42,29,0.690476,0

In [20]:
import pandas as pd
import numpy as np

# THE RAW, MESSY DATA
raw_data = {
    "Match_ID": [101, 101, 102, 103, 103, 104],
    "Player": ["Vinicius Jr", "Bellingham", "Rashford", "Fernandes", "Mainoo", "Rodrygo"],
    "Club": ["Real Madrid", "Real Madrid", "Man Utd", "Man Utd", "Man Utd", "Real Madrid"],
    "Role": ["Attacker", "Midfielder", "Attacker", "Midfielder", "Midfielder", "Attacker"],
    "Distance_km": [10.2, 11.8, np.nan, 12.1, 11.5, 9.8], # Rashford's tracker broke
    "Passes_Attempted": [40, 65, 35, 80, 55, np.nan],     # Rodrygo's pass data missing
    "Passes_Completed": [32, 58, 25, 60, 49, 38]
}

df = pd.DataFrame(raw_data)

# --- CAPSTONE PIPELINE ---

# TODO 1: Handle the Chaos.
# Rashford's distance is missing. Fill any NaN in "Distance_km" with the MEAN of the "Distance_km" column.
df["Distance_km"] = df["Distance_km"].fillna(df["Distance_km"].mean())
# Rodrygo's passes attempted is missing. We will use amputation here. Drop any rows that STILL contain a NaN value.
df = df.dropna(axis=0)


# TODO 2: Feature Engineering.
# Create a new column called "Pass_Accuracy" (Passes_Completed divided by Passes_Attempted).
df["Pass_Accuracy"] = df["Passes_Completed"] / df["Passes_Attempted"]

# TODO 3: Tactical Slicing.
# Create a new DataFrame called 'midfielders_df' that ONLY contains players where the "Role" is "Midfielder".
midfielders_df = df[df["Role"] == "Midfielder"]


# TODO 4: Grouping & Aggregation.
# Using your new 'midfielders_df', group by "Club" and calculate:
# - The mean of "Distance_km"
# - The mean of your newly engineered "Pass_Accuracy"
# Save this final matrix to a variable called 'final_tactical_summary'.
final_tactical_summary = midfielders_df.groupby("Club").agg({
    "Distance_km": 'mean',
    "Pass_Accuracy": 'mean',
})

In [21]:
df

,Match_ID,Player,Club,Role,Distance_km,Passes_Attempted,Passes_Completed,Pass_Accuracy
0,101,Vinicius Jr,Real Madrid,Attacker,10.20,40.0,32,0.800000
1,101,Bellingham,Real Madrid,Midfielder,11.80,65.0,58,0.892308
2,102,Rashford,Man Utd,Attacker,11.08,35.0,25,0.714286
3,103,Fernandes,Man Utd,Midfielder,12.10,80.0,60,0.750000
4,103,Mainoo,Man Utd,Midfielder,11.50,55.0,49,0.890909

In [22]:
midfielders_df

,Match_ID,Player,Club,Role,Distance_km,Passes_Attempted,Passes_Completed,Pass_Accuracy
1,101,Bellingham,Real Madrid,Midfielder,11.8,65.0,58,0.892308
3,103,Fernandes,Man Utd,Midfielder,12.1,80.0,60,0.750000
4,103,Mainoo,Man Utd,Midfielder,11.5,55.0,49,0.890909

In [23]:
final_tactical_summary

             Distance_km  Pass_Accuracy
Club
Man Utd             11.8       0.820455
Real Madrid         11.8       0.892308